# Generated by Django 5.2.2 on 2025-06-08 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='remind_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 20, 11, 54, 593072)),
        ),
    ]
