# Generated by Django 5.2.2 on 2025-06-08 16:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_App', '0002_remove_reminder_date_remove_reminder_remind_by_and_more'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.userdata'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 21, 48, 30, 671868)),
        ),
    ]
