# Generated by Django 5.2.2 on 2025-06-08 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_App', '0003_reminder_user_alter_reminder_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='location',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 22, 29, 56, 600239)),
        ),
    ]
