# Generated by Django 5.2.2 on 2025-06-09 11:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_App', '0004_reminder_location_alter_reminder_date_time'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 17, 10, 53, 386921)),
        ),
        migrations.CreateModel(
            name='PastReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2025, 6, 9, 17, 10, 53, 386921))),
                ('location', models.CharField(default='')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.userdata')),
            ],
        ),
    ]
