# Generated by Django 5.2.3 on 2025-07-08 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_App', '0005_alter_reminder_date_time_pastreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastreminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 14, 33, 12, 715694)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 14, 33, 12, 715269)),
        ),
    ]
