# Generated by Django 5.2.6 on 2025-09-21 14:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_App', '0010_alter_pastreminder_date_time_and_more'),
        ('login', '0002_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastreminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 21, 19, 43, 15, 775099)),
        ),
        migrations.AlterField(
            model_name='pastreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 21, 19, 43, 15, 774176)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata'),
        ),
    ]
