# Generated by Django 5.2.3 on 2025-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Tejas', max_length=10)),
                ('last_name', models.CharField(default='Varute', max_length=10)),
            ],
        ),
    ]
